services:
  - type: web
    name: avprop-mission
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
